version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: postgresql_dev
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=devldpcom
    restart: always
    volumes:
      - postgresql_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
volumes:
  postgresql_dev: